services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    env_file:
      - .env.${NODE_ENV:-development}
    volumes:
      - ./backend/db:/usr/src/app/db

  scheduler:
    build:
      context: ./backend
    env_file:
      - .env.${NODE_ENV:-development}
    volumes:
      - ./backend/db:/usr/src/app/db
    command: [ "node", "scheduler.js" ]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env.${NODE_ENV:-development}
